sudo: false

env: 
  - DB_ADDRESS=localhost:27017 DB_NAME=gams DB_USER=poe DB_PASSWORD=fortunato PORT 4044

services: mongodb

language: node_js

node_js:
  - node

install:
  - npm install

before_script:
  - sleep 15
  - mongo gams --eval 'db.createUser({user:"poe",pwd:"fortunato",roles:["readWrite"]});'

script:
  - npm test
