sudo: false

services: mongodb

language: node_js

node_js:
  - node

install:
  - npm install

before_script:
  - sleep 15
  - mongo gams --eval 'db.createUser({user:"poe",pwd:"fortunato",roles:["readWrite"]});'

script:
  - npm test
